### ISSUE TITLE
Concentration skill changed, site description is now inaccurate

### ISSUE THREAD

**Issue by Squishy3000** [MagiCircles/CinderellaProducers#27]
Rather than "...but all other notes will break your combo in the next X seconds.", the description for Concentration should be "...but the timing window for Perfect notes is reduced in the next X seconds.", to reflect the change made to the Concentration skill in a November 2017 patch for the game.

**Comment by db0company** [comment]
Japanese `⎾{trigger_chance}%の確率 - {skill_duration}秒⏌ -  {trigger_value}秒毎、高確率でわずかな間、PERFECTのスコア{skill_value}%アップ、PERFECT判定される時間が短くなる`
